version: 2.1

workflows:
  my-workflow:
    jobs:
      - test-circle-ci-add-branch:
          name: job 1
          filters:
            branches:
              only:
                - circle-ci-add
      - test_release-next:
          name: job 2
          filters:
            branches:
              only:
                - release-next
          requires:
            - "job 1"

jobs:
  test-circle-ci-add-branch:
    docker:
      - image: cimg/aws:2023.07
    steps:
      - checkout
      - run:
          name: check version
          command: aws --version
      - run:
          name: echo etwas
          command: echo "hello from circle-ci-add-branch"

  test_release-next:
    docker:
      - image: cimg/aws:2023.07
    steps:
      - checkout
      - run:
          name: trn
          command: echo "hello from release-next"